services:
  ingestion:
    platform: linux/amd64
    image: python:3.12.7-alpine3.20
    environment:
      - EVENTS_TOPIC_ID=events_topic
      - STATUS_TOPIC_ID=status_topic
      - PROJECT_ID=jobsity-challenge-vitor
      - CSV_PROCESSED_FOLDER=processed
      - GOOGLE_APPLICATION_CREDENTIALS=/home/user/gcp_credentials.json
    volumes:
      - ./ingestion-service:/home/user/
    ports:
      - "8000:8000"
    working_dir: /home/user
    command: /bin/sh -c "pip3 install -r requirements.txt && fastapi run main.py"
  ui:
    platform: linux/amd64
    image: python:3.12.7-alpine3.20
    environment:
      - PROJECT_ID=jobsity-challenge-vitor
      - DATASET_ID=trips
      - TABLE_ID=trips
      - GOOGLE_APPLICATION_CREDENTIALS=/home/user/gcp_credentials.json
    volumes:
      - ./ui-service:/home/user/
    ports:
      - "8001:8001"
    working_dir: /home/user
    command: /bin/sh -c "pip3 install -r requirements.txt && fastapi run --port 8001 main.py"
